# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
-   repo: https://github.com/dnephin/pre-commit-golang
    rev: v0.5.0
    hooks:
    -   id: go-fmt
    -   id: go-vet
    -   id: go-imports
    -   id: go-cyclo
        args: [-over=15]
    -   id: validate-toml
    -   id: no-go-testing
    -   id: go-unit-tests
    -   id: go-build
    -   id: go-mod-tidy
-   repo: https://github.com/golangci/golangci-lint
    rev: v1.41.1
    hooks:
    -   id: golangci-lint
-   repo: https://github.com/pre-commit/mirrors-eslint
    rev: 'v7.18.0'
    hooks:
    -   id: eslint
    types: [file]
    types_or: [javascript, jsx, ts, tsx, vue]
    args: [-max-len, 79]
    additional_dependencies:
    -   eslint-plugin-vue@v7.5.0
